// Copy de Pagos y bancos (/admin/pagos). Aparte de site.ts para no mezclar el panel con la tienda.
export const paymentsCopy = {
  title: 'Pagos y bancos',
  subtitle: 'Transferencias, recargo y cuentas bancarias',
  switchLabel: 'Aceptar transferencias bancarias',
  switchOn: 'Activo: tus clientes ven la opción de transferencia',
  switchOff: 'Apagado: la web y el bot no ofrecen transferencia',
  needsAccount: 'Agrega al menos una cuenta para activarlo',
  activated: 'Transferencias activadas',
  deactivated: 'Transferencias apagadas',
  activeCount: (n: number) => (n === 1 ? '1 cuenta activa' : `${n} cuentas activas`),
  surchargeTitle: 'Recargo por transferencia',
  surchargeHint: 'Se suma al total cuando el cliente paga por transferencia. 0 si no cobras extra.',
  surchargeSave: 'Guardar recargo',
  surchargeSaved: 'Recargo guardado',
  accountsTitle: 'Cuentas bancarias',
  addAccount: 'Agregar cuenta',
  emptyTitle: 'Aún no hay cuentas',
  emptyText: 'Agrega la cuenta donde tus clientes te transfieren. Puedes tener varias y pausarlas cuando quieras.',
  active: 'Activa',
  paused: 'Pausada',
  show: 'Ver número',
  hide: 'Ocultar número',
  edit: 'Editar',
  remove: 'Eliminar',
  holder: 'Titular',
  idNumber: 'Cédula/RUC',
  account: (type: string) => (type === 'Transaccional' ? 'Cuenta transaccional' : `Cuenta de ${type.toLowerCase()}`),
  deleteTitle: '¿Eliminar esta cuenta?',
  deleteText: (bank: string, last4: string) =>
    `${bank} terminada en ${last4} deja de mostrarse en la web, los correos y el bot. Los pedidos ya hechos no cambian.`,
  deleteConfirm: 'Sí, eliminar',
  deleted: 'Cuenta eliminada',
  accountPaused: 'Cuenta pausada',
  accountResumed: 'Cuenta activa',
  formNew: 'Nueva cuenta',
  formEdit: 'Editar cuenta',
  bankLabel: 'Banco o cooperativa',
  bankSearch: 'Busca tu banco',
  bankNone: 'No está en la lista: elige "Otro banco o cooperativa"',
  otherName: 'Nombre del banco o cooperativa',
  typeLabel: 'Tipo de cuenta',
  numberLabel: 'Número de cuenta',
  holderLabel: 'Titular',
  idLabel: 'Cédula o RUC del titular',
  cancel: 'Cancelar',
  save: 'Guardar cuenta',
  saved: 'Cuenta guardada',
  previewTitle: 'Así lo ve tu cliente',
  previewText: 'En la página de su pedido y en el correo de confirmación.',
  previewEmpty: 'Cuando actives una cuenta, aquí ves cómo le llega al cliente.',
  settingsLink: 'Gestionar en Pagos y bancos',
  errors: {
    bank: 'Elige el banco',
    otherName: 'Escribe el nombre del banco',
    number: 'Solo dígitos, entre 5 y 20',
    holder: 'Escribe el nombre del titular',
    idNumber: 'Cédula de 10 dígitos o RUC de 13',
  },
} as const
